version: '2.4'

services:
  postgres:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
    volumes:
      - ./db-data:/var/lib/postgresql/data
