version: '2.4'

services:
  api:
    build:
      context: .
      target: dev
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - .:/node/app
      - /node/app/node_modules
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  # postgres:
  #   build:
  #     context: ../postgres
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5432:5432
  #   healthcheck:
  #     test: pg_isready -U postgres -h 127.0.0.1
  #   volumes:
  #     - ../postgres/db-data:/var/lib/postgresql/data